spring.application.name=TestAI
spring.ai.openai.api-key=AIzaSyDWwFw3MT0-1_AnBgm-S8NbYz8aRsxqLh0

spring.ai.openai.base-url=https://generativelanguage.googleapis.com/v1beta/openai

spring.ai.openai.chat.options.model=gemini-1.5-flash